# nixpacks.toml

[phases.setup]
# A list of system packages to install using apt-get
pkgs = [
  "libmagic-dev",
  "poppler-utils",
  "tesseract-ocr",
  "tesseract-ocr-all", # This installs all available language packs for tesseract-lang
  "libreoffice",
  "pandoc",
  "libgl1",
  "libglx-mesa0"
]
